# Generated by Django 4.0.2 on 2022-02-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0002_alter_review_body_alter_review_headline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
